services:
  db:
    image: postgres:16.0-alpine3.17
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - my_db:$PGDATA

  redis:
    image: redis:latest
    env_file:
      - .env
    ports:
      - "6379:6379"
    
  library:
      build:
        context: .
        dockerfile: Dockerfile
      env_file:
        - .env
      ports:
        - "8001:8000"
      volumes:
        - .:/app
      command: >
        sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
      depends_on:
        - db
        - redis
  
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
        sh -c "python manage.py wait_for_db &&
              celery -A library_service worker -l info"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
    - library
    - redis
    - db
    restart: on-failure    

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: >
        sh -c "python manage.py wait_for_db &&
              celery -A library_service beat -l info" 
    depends_on:
      - library
      - redis
      - db
    restart: on-failure
    volumes:
      - .:/app

volumes:
  my_db: