# Generated by Django 5.1.4 on 2024-12-26 14:25

import django.db.models.deletion
import django_enum.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowing', '0002_alter_borrowing_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_enum.fields.EnumCharField(blank=True, choices=[('pending', 'Pending'), ('paid', 'Paid')], max_length=7, null=True)),
                ('type', django_enum.fields.EnumCharField(blank=True, choices=[('payment', 'Payment'), ('fine', 'Fine')], max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('session_url', models.URLField(blank=True, null=True)),
                ('money_to_pay', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('borrowing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowing.borrowing')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'paid']), ('status__isnull', True), _connector='OR'), name='payment_Payment_status_PaymentStaus'), models.CheckConstraint(condition=models.Q(('type__in', ['payment', 'fine']), ('type__isnull', True), _connector='OR'), name='payment_Payment_type_PaymentType')],
            },
        ),
    ]
