# Generated by Django 5.1.4 on 2024-12-27 10:47

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0002_alter_borrowing_options_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='borrowing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='borrowing.borrowing'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=django_enum.fields.EnumCharField(blank=True, choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=django_enum.fields.EnumCharField(blank=True, choices=[('payment', 'Payment'), ('fine', 'Fine')], default='payment', max_length=7, null=True),
        ),
    ]
