# Generated by Django 5.1.4 on 2024-12-28 12:22

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0002_alter_borrowing_options_and_more'),
        ('payment', '0002_alter_payment_borrowing_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='payment_Payment_status_PaymentStaus',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=django_enum.fields.EnumCharField(blank=True, choices=[('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired')], default='pending', max_length=7, null=True),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'paid', 'expired']), ('status__isnull', True), _connector='OR'), name='payment_Payment_status_PaymentStatus'),
        ),
    ]
