# Generated by Django 5.1.4 on 2024-12-20 18:12

import django_enum.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=120)),
                ('daily_fee', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('cover', django_enum.fields.EnumCharField(blank=True, choices=[('Hardcover', 'Hard'), ('Paperback', 'Soft')], max_length=9, null=True)),
                ('inventory', models.PositiveSmallIntegerField(blank=True, default=0)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('cover__in', ['Hardcover', 'Paperback']), ('cover__isnull', True), _connector='OR'), name='books_Book_cover_BookCoverType')],
            },
        ),
    ]
