# Generated by Django 5.1.4 on 2024-12-22 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('borrowing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowing',
            options={'ordering': ['-borrow_date']},
        ),
        migrations.AddConstraint(
            model_name='borrowing',
            constraint=models.CheckConstraint(condition=models.Q(('expected_return_date__gt', models.F('borrow_date'))), name='expected_return_date_after_borrow_date'),
        ),
    ]
