name: Test

on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set Up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest

      - name: Run flake8
        run: flake8 
    
      - name: Run pytest
        run: pytest
